/**
 * RunController — all of the console's game logic in plain TypeScript.
 * Plan §4.2, §4.6, §7 T5. No runes, no DOM; `Storage` and the wall clock
 * are injected so `bun test` drives it with a `MemStorage` and a fake `now`.
 *
 * The controller owns one run: its state, its event log, its wall-clock
 * record and the memoised selectors the rooms read. Every write goes
 * through `dispatch`; every advance goes through `advance`. Only the log is
 * saved; state is regenerated by `replay`, which is exact (§3.7).
 */
import type { Action, SimConfig, SimEvent, SimState } from '../../sim/types';
import { createRng, type Rng } from '../../sim/rng';
import { PRELUDE_HOURS, hoursDue, type SimSpeed } from '../../sim/time';
import { DEFAULT_CONFIG } from '../../sim/constants';
import {
  advanceTo,
  appendAction,
  appendCheckpoint,
  applyAction,
  createState,
  isCheckpointHour,
  newLog,
  replay,
  verifyCheckpoints,
} from '../../sim/events';
import {
  fleetDetail,
  fleetSummaries,
  headline,
  openIncidents,
  projectedZero,
  routingTable,
  runwayMonths,
  runwayWeeks,
  slopePerWeek,
  weeksBought,
  type FleetDetail,
  type FleetSummary,
  type HeadlineSignal,
  type Incident,
  type ProjectedZero,
  type RoutingTable,
  type WeeksBought,
} from '../../sim/metrics';
import { explore, type ExploreQuery, type ExploreResult } from '../../sim/explore';
import { load, save, type SaveRecord } from '../persistence';

/** Where the run is on the wall clock; saved alongside the log. */
export interface TimeRecord {
  /** state.t at the time of the record. */
  t: number;
  /** Wall-clock ms of the last settlement; paused time never accrues. */
  stampMs: number;
  paused: boolean;
  speed: SimSpeed;
  /** Wall-clock ms owed but not yet a whole sim-hour. */
  carryMs: number;
}

/** Every advance, manual or tick-driven, reports what changed. */
export interface AdvanceReport {
  hours: number;
  cashDelta: number;
  slopeBefore: number;
  slopeAfter: number;
  /** Weeks; null = climbing. */
  runwayBefore: number | null;
  runwayAfter: number | null;
}

/** The bought-weeks badge's source; only ever set after an action. */
export interface Payoff {
  atT: number;
  actionT: number;
  hoursSinceAction: number;
  bought: WeeksBought;
}

/** An action pays off only once this many sim-hours have passed since it. */
export const PAYOFF_MIN_HOURS = 24;

/** Debounce for `scheduleSave`. */
export const SAVE_DEBOUNCE_MS = 250;

export interface RunDeps {
  storage?: Storage | null;
  now?: () => number;
  config?: SimConfig;
}

export interface PendingAction {
  t: number;
  runwayWeeks: number | null;
}

export interface AwaySummary {
  hours: number;
  cashDelta: number;
}

type Listener = (run: RunController) => void;

function assertHours(hours: number): void {
  if (!Number.isInteger(hours) || hours < 0) throw new RangeError(`advance: hours must be a non-negative integer, got ${hours}`);
}

export class RunController {
  state!: SimState;
  log: SimEvent[] = [];
  seed = 0;
  readonly config: SimConfig;
  rng: Rng;
  time: TimeRecord = { t: 0, stampMs: 0, paused: false, speed: 1, carryMs: 0 };

  lastAdvance: AdvanceReport | null = null;
  awaySummary: AwaySummary | null = null;
  payoff: Payoff | null = null;
  pendingAction: PendingAction | null = null;
  /** True when `boot()` created the run. TODO(intro): the intro sequence gates on this. */
  isFirstLogin = false;
  /** Set by `boot` when a saved log fails its checkpoint check (replay is trusted regardless). */
  checkpointMismatchT: number | null = null;

  private readonly storage: Storage | null;
  private readonly now: () => number;
  private readonly listeners = new Set<Listener>();
  private saveTimer: ReturnType<typeof setTimeout> | null = null;
  private memoState: SimState | null = null;
  private readonly memoCache = new Map<string, unknown>();

  constructor(deps: RunDeps = {}) {
    this.storage = deps.storage ?? null;
    this.now = deps.now ?? (() => Date.now());
    this.config = deps.config ?? DEFAULT_CONFIG;
    this.rng = createRng(0);
  }

  get booted(): boolean {
    return this.state !== undefined;
  }

  // -------------------------------------------------------------------------
  // Lifecycle
  // -------------------------------------------------------------------------

  /**
   * Load the saved run if there is one (replay, verify checkpoints, catch up
   * on the wall clock unless paused), otherwise start a new run. Saves either way.
   */
  boot(nowMs: number = this.now()): void {
    const rec = load(this.storage, this.config.constants.SIM_VERSION);
    if (rec && this.restore(rec, nowMs)) {
      this.isFirstLogin = false;
    } else {
      this.newRun(undefined, nowMs);
      this.isFirstLogin = true;
    }
    this.saveNow();
  }

  /** Rebuild from a record; false when the log does not replay. */
  private restore(rec: SaveRecord, nowMs: number): boolean {
    let state: SimState;
    try {
      state = replay(rec.log, rec.time.t, this.config);
    } catch {
      return false;
    }
    this.seed = rec.seed;
    this.log = rec.log.slice();
    this.rng = createRng(rec.seed);
    this.state = state;
    this.time = { ...rec.time, t: state.t };
    this.lastAdvance = null;
    this.awaySummary = null;
    this.payoff = null;
    this.pendingAction = null;
    this.invalidate();

    const check = verifyCheckpoints(this.log, this.config);
    this.checkpointMismatchT = check.ok ? null : check.firstMismatchT;
    if (!check.ok && typeof console !== 'undefined') {
      console.warn(`[run] checkpoint mismatch at t=${check.firstMismatchT}; trusting replay`);
    }

    // Wall-clock catch-up: what the run owes for the time the tab was away.
    if (!this.time.paused) {
      const cashBefore = this.state.cash;
      const hours = this.settle(nowMs);
      if (hours > 0) this.awaySummary = { hours, cashDelta: this.state.cash - cashBefore };
    }
    this.emit();
    return true;
  }

  /** Start over with `seed` (default: the wall clock). TODO(prestige): carried artifacts. */
  newRun(seed?: number, nowMs: number = this.now()): void {
    const s = seed === undefined ? nowMs >>> 0 : seed >>> 0;
    this.seed = s;
    this.rng = createRng(s);
    this.state = createState(s, this.config);
    this.log = newLog(s, nowMs, this.config);
    this.time = { t: this.state.t, stampMs: nowMs, paused: false, speed: 1, carryMs: 0 };
    this.lastAdvance = null;
    this.awaySummary = null;
    this.payoff = null;
    this.pendingAction = null;
    this.checkpointMismatchT = null;
    this.isFirstLogin = false;
    this.invalidate();
    this.emit();
    this.saveNow();
  }

  // -------------------------------------------------------------------------
  // Time
  // -------------------------------------------------------------------------

  /**
   * Step the sim `hours` forward, appending a checkpoint at every multiple
   * of CHECKPOINT_EVERY_HOURS crossed (the checkpoint hashes the state at
   * that hour, before any action dispatched at it, matching replay order).
   * Then, iff an action is pending and at least PAYOFF_MIN_HOURS have passed
   * since it, compute the payoff and clear the pending action. Advances
   * with nothing pending never touch `payoff`.
   */
  advance(hours: number): AdvanceReport {
    assertHours(hours);
    this.assertBooted();
    const before = this.state;
    const slopeBefore = this.slope();
    const runwayBefore = this.runwayWeeks();

    if (hours > 0 && before.status !== 'bankrupt') {
      const every = this.config.constants.CHECKPOINT_EVERY_HOURS;
      const end = before.t + hours;
      let s = before;
      // Next checkpoint hour strictly after s.t, then every `every` hours.
      let next = nextCheckpointAfter(s.t, every);
      while (next <= end) {
        s = advanceTo(s, next, this.config, this.rng);
        if (isCheckpointHour(s.t, this.config)) this.log = appendCheckpoint(this.log, s);
        next += every;
      }
      s = advanceTo(s, end, this.config, this.rng);
      this.state = s;
      this.time = { ...this.time, t: s.t };
      this.invalidate();
    }

    const report: AdvanceReport = {
      hours,
      cashDelta: this.state.cash - before.cash,
      slopeBefore,
      slopeAfter: this.slope(),
      runwayBefore,
      runwayAfter: this.runwayWeeks(),
    };
    this.lastAdvance = report;

    const pending = this.pendingAction;
    if (pending && this.state.t - pending.t >= PAYOFF_MIN_HOURS) {
      const hoursSinceAction = this.state.t - pending.t;
      this.payoff = {
        atT: this.state.t,
        actionT: pending.t,
        hoursSinceAction,
        bought: weeksBought(pending.runwayWeeks, this.runwayWeeks(), hoursSinceAction, this.config),
      };
      this.pendingAction = null;
    }

    this.scheduleSave();
    this.emit();
    return report;
  }

  /** Wall-clock catch-up: advance whatever `hoursDue` says is owed. Returns hours advanced. */
  tick(nowMs: number = this.now()): number {
    this.assertBooted();
    if (this.time.paused) return 0;
    return this.settle(nowMs);
  }

  /** Move the stamp to `nowMs`, keep the carry, advance the whole hours owed. */
  private settle(nowMs: number): number {
    const due = hoursDue(this.time.stampMs, nowMs, this.time.speed, this.time.carryMs);
    this.time = { ...this.time, stampMs: nowMs, carryMs: due.carryMs };
    if (due.hours > 0) {
      this.advance(due.hours);
    } else {
      this.emit();
    }
    return due.hours;
  }

  pause(): void {
    this.assertBooted();
    if (this.time.paused) return;
    this.settle(this.now()); // owe nothing across the pause
    this.time = { ...this.time, paused: true };
    this.emit();
    this.saveNow();
  }

  /** Resume: the stamp moves to now, so paused wall time never accrues. */
  resume(): void {
    this.assertBooted();
    if (!this.time.paused) return;
    this.time = { ...this.time, paused: false, stampMs: this.now() };
    this.emit();
    this.saveNow();
  }

  /** Settle at the old speed first, so the change never re-prices time already owed. */
  setSpeed(speed: SimSpeed): void {
    this.assertBooted();
    if (!this.time.paused) this.settle(this.now());
    this.time = { ...this.time, speed };
    this.emit();
    this.saveNow();
  }

  // -------------------------------------------------------------------------
  // Actions — the only write path
  // -------------------------------------------------------------------------

  dispatch(action: Action): void {
    this.assertBooted();
    this.log = appendAction(this.log, this.state, action, this.now());
    this.state = applyAction(this.state, action);
    this.invalidate();
    // The first action since the last payoff sets the baseline the badge measures from.
    this.pendingAction ??= { t: this.state.t, runwayWeeks: this.runwayWeeks() };
    this.emit();
    this.saveNow();
  }

  // -------------------------------------------------------------------------
  // Persistence
  // -------------------------------------------------------------------------

  record(): SaveRecord {
    return { version: this.config.constants.SIM_VERSION, seed: this.seed, log: this.log, time: { ...this.time } };
  }

  saveNow(): void {
    if (this.saveTimer !== null) {
      clearTimeout(this.saveTimer);
      this.saveTimer = null;
    }
    if (!this.booted) return;
    save(this.record(), this.storage);
  }

  /** Debounced save; timers are guarded so a non-DOM host simply saves at once. */
  scheduleSave(): void {
    if (typeof setTimeout !== 'function') {
      this.saveNow();
      return;
    }
    if (this.saveTimer !== null) clearTimeout(this.saveTimer);
    const timer = setTimeout(() => {
      this.saveTimer = null;
      this.saveNow();
    }, SAVE_DEBOUNCE_MS);
    // Never keep a test process alive for a pending save.
    (timer as { unref?: () => void }).unref?.();
    this.saveTimer = timer;
  }

  onChange(cb: Listener): () => void {
    this.listeners.add(cb);
    return () => {
      this.listeners.delete(cb);
    };
  }

  private emit(): void {
    for (const cb of this.listeners) cb(this);
  }

  // -------------------------------------------------------------------------
  // Selectors (memoised on state identity)
  // -------------------------------------------------------------------------

  private assertBooted(): void {
    if (!this.booted) throw new Error('RunController: boot() or newRun() first');
  }

  private invalidate(): void {
    this.memoState = null;
    this.memoCache.clear();
  }

  private memo<T>(key: string, compute: () => T): T {
    this.assertBooted();
    if (this.memoState !== this.state) {
      this.memoState = this.state;
      this.memoCache.clear();
    }
    if (this.memoCache.has(key)) return this.memoCache.get(key) as T;
    const value = compute();
    this.memoCache.set(key, value);
    return value;
  }

  runwayMonths(): number | null {
    return this.memo('runwayMonths', () => runwayMonths(this.state, this.config));
  }

  runwayWeeks(): number | null {
    return this.memo('runwayWeeks', () => runwayWeeks(this.state, this.config));
  }

  slope(): number {
    return this.memo('slope', () => slopePerWeek(this.state, this.config));
  }

  headline(): HeadlineSignal[] {
    return this.memo('headline', () => headline(this.state, this.config));
  }

  incidents(): Incident[] {
    return this.memo('incidents', () => openIncidents(this.state, this.config));
  }

  fleets(): FleetSummary[] {
    return this.memo('fleets', () => fleetSummaries(this.state, this.config));
  }

  fleet(id: string): FleetDetail | null {
    return this.memo(`fleet:${id}`, () => fleetDetail(this.state, id, this.config));
  }

  routing(): RoutingTable {
    return this.memo('routing', () => routingTable(this.state, this.config));
  }

  explore(q: ExploreQuery): ExploreResult {
    const key = `explore:${q.range}:${q.groupBy}:${q.top ?? ''}:${q.fleetId ?? ''}`;
    return this.memo(key, () => explore(this.state, q, this.config));
  }

  projectedZero(): ProjectedZero | null {
    return this.memo('projectedZero', () => projectedZero(this.state, this.config));
  }

  paletteFleets(): { id: string; name: string; role: string }[] {
    return this.memo('paletteFleets', () => {
      const w = this.state.world;
      return w.fleetOrder.map((id) => ({ id, name: w.fleets[id].name, role: w.fleets[id].role }));
    });
  }
}

/** The first checkpoint hour (every `every` hours from login) strictly after `t`. */
function nextCheckpointAfter(t: number, every: number): number {
  return PRELUDE_HOURS + (Math.floor((t - PRELUDE_HOURS) / every) + 1) * every;
}
