/**
 * Genesis, the event log and replay. Plan §3.1, §3.7 (T3).
 *
 * `createState(seed)` generates the world and runs the 28-day prelude so the
 * player logs in to a full hourly ring and daily history. Only the log is
 * ever persisted; state is regenerated by `replay`, which is exact because
 * noise is a pure function of `(seed, t)` and actions apply at integer hours.
 */
import type {
  Action,
  Constants,
  DaySample,
  FleetPolicy,
  FleetRuntime,
  HourSample,
  RoutingRule,
  SimConfig,
  SimEvent,
  SimState,
  WorldPhysics,
} from './types';
import { createRng, fnv1a, type Rng } from './rng';
import { PRELUDE_HOURS } from './time';
import { generateWorld } from './world';
import { DEFAULT_CONFIG } from './constants';
import { step } from './step';

/** Retry attempts are clamped to this range by `applyAction`. */
export const MIN_RETRY_ATTEMPTS = 1;
export const MAX_RETRY_ATTEMPTS = 5;

/** TODO(prestige): called once when a run goes bankrupt; the post-mortem reads the final state. */
export type PostMortemHook = (state: SimState) => void;

/** The six physics numbers the generator and `step.ts` must agree on. */
export function physicsOf(c: Constants): WorldPhysics {
  return {
    prefillTps: c.PREFILL_TPS,
    overheadS: c.JOB_OVERHEAD_S,
    diurnalAmplitude: c.DIURNAL_AMPLITUDE,
    hoursPerMonth: c.HOURS_PER_MONTH,
    trivialMax: c.SIZE_CLASS_TRIVIAL_MAX,
    standardMax: c.SIZE_CLASS_STANDARD_MAX,
  };
}

/** Rules are kept sorted by (priority, id) so ordering is never ambiguous. */
export function sortRules(rules: readonly RoutingRule[]): RoutingRule[] {
  return rules.slice().sort((a, b) => a.priority - b.priority || (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
}

function initialRuntime(policy: FleetPolicy, stormExcess: number, slots: number): FleetRuntime {
  return {
    policy: { ...policy, retry: { ...policy.retry } },
    queueDepth: 0,
    errorRate: 0,
    stormExcess,
    attemptsPerJob: 0,
    utilization: 0,
    slotsNeeded: 0,
    slotsProvisioned: slots,
    breakerOpen: false,
    slaBreached: false,
  };
}

/** Genesis: the world at t = 0 with an empty ledger and cash 0. */
export function genesis(seed: number, config: SimConfig = DEFAULT_CONFIG): SimState {
  const c = config.constants;
  const world = generateWorld(seed, c.world, c.TIERS, physicsOf(c));
  const fleets: Record<string, FleetRuntime> = {};
  for (const id of world.fleetOrder) {
    const f = world.fleets[id];
    fleets[id] = initialRuntime(f.initialPolicy, f.initialStormExcess, f.initialPolicy.concurrency);
  }
  return {
    version: c.SIM_VERSION,
    seed,
    t: 0,
    cash: 0,
    status: 'running',
    bankruptAt: null,
    world,
    fleets,
    routing: sortRules(world.routing),
    hourly: [],
    daily: [],
    dayAcc: null,
    totals: { revenue: 0, tokenCost: 0, capacityCost: 0, opex: 0, tokens: 0 },
  };
}

/**
 * Genesis + prelude. Cash accumulates net (from 0) through the prelude; at
 * login it is set to OPENING_CASH and every recorded `cashClose` is shifted
 * by the same amount, which is exact because costs never depend on cash.
 */
export function createState(seed: number, config: SimConfig = DEFAULT_CONFIG): SimState {
  const c = config.constants;
  const rng = createRng(seed);
  const s = step(genesis(seed, config), PRELUDE_HOURS, config, rng);
  const netAtLogin = s.cash;
  const shift = (sample: number): number => c.OPENING_CASH - (netAtLogin - sample);
  const hourly: HourSample[] = s.hourly.map((h) => ({ ...h, cashClose: shift(h.cashClose) }));
  const daily: DaySample[] = s.daily.map((d) => ({ ...d, cashClose: shift(d.cashClose) }));
  const dayAcc = s.dayAcc ? { ...s.dayAcc, cashClose: shift(s.dayAcc.cashClose) } : null;
  return { ...s, cash: c.OPENING_CASH, hourly, daily, dayAcc };
}

// ---------------------------------------------------------------------------
// Actions
// ---------------------------------------------------------------------------

function clampInt(x: number, lo: number, hi: number): number {
  return Math.min(Math.max(Math.round(x), lo), hi);
}

/** Apply one action at the current hour. Unknown fleet or rule → the same state object. */
export function applyAction(state: SimState, action: Action): SimState {
  switch (action.type) {
    case 'routing.set': {
      const rule: RoutingRule = { ...action.rule, match: { ...action.rule.match } };
      const rest = state.routing.filter((r) => r.id !== rule.id);
      return { ...state, routing: sortRules(rest.concat([rule])) };
    }
    case 'routing.remove': {
      if (!state.routing.some((r) => r.id === action.ruleId)) return state;
      return { ...state, routing: state.routing.filter((r) => r.id !== action.ruleId) };
    }
    case 'fleet.policy': {
      const prev = state.fleets[action.fleetId];
      if (!prev) return state;
      const { retry: retryPatch, ...rest } = action.patch;
      const policy: FleetPolicy = { ...prev.policy, ...rest, retry: { ...prev.policy.retry, ...(retryPatch ?? {}) } };
      policy.concurrency = Math.max(0, Number.isFinite(policy.concurrency) ? policy.concurrency : 0);
      policy.retry.maxAttempts = clampInt(
        Number.isFinite(policy.retry.maxAttempts) ? policy.retry.maxAttempts : MIN_RETRY_ATTEMPTS,
        MIN_RETRY_ATTEMPTS,
        MAX_RETRY_ATTEMPTS,
      );
      return { ...state, fleets: { ...state.fleets, [action.fleetId]: { ...prev, policy } } };
    }
    default:
      return state;
  }
}

/** Step forward to sim-hour `t` (no-op when already there or past it). */
export function advanceTo(state: SimState, t: number, config: SimConfig, rng: Rng): SimState {
  return t > state.t ? step(state, t - state.t, config, rng) : state;
}

// ---------------------------------------------------------------------------
// The log
// ---------------------------------------------------------------------------

/** A fresh log: `[run.start]` at login. */
export function newLog(seed: number, wallMs: number, config: SimConfig = DEFAULT_CONFIG): SimEvent[] {
  return [{ type: 'run.start', t: PRELUDE_HOURS, seed, wallMs, version: config.constants.SIM_VERSION }];
}

/** Returns a new log with the action stamped at `state.t`; the input log is not mutated. */
export function appendAction(log: readonly SimEvent[], state: SimState, action: Action, wallMs: number): SimEvent[] {
  return log.concat([{ ...action, t: state.t, wallMs } as SimEvent]);
}

/** fnv1a-32 over `t | cash.toFixed(4) | totals.tokens.toFixed(0) | per-fleet queue.toFixed(3)`. */
export function hashState(state: SimState): string {
  const parts = [String(state.t), state.cash.toFixed(4), state.totals.tokens.toFixed(0)];
  for (const id of state.world.fleetOrder) parts.push(state.fleets[id].queueDepth.toFixed(3));
  return fnv1a(parts.join('|')).toString(16).padStart(8, '0');
}

/** Returns a new log with a checkpoint of `state` appended. */
export function appendCheckpoint(log: readonly SimEvent[], state: SimState): SimEvent[] {
  return log.concat([{ type: 'checkpoint', t: state.t, hash: hashState(state) }]);
}

/** True when `t` is a checkpoint hour (every CHECKPOINT_EVERY_HOURS from login). */
export function isCheckpointHour(t: number, config: SimConfig = DEFAULT_CONFIG): boolean {
  const every = config.constants.CHECKPOINT_EVERY_HOURS;
  return t > PRELUDE_HOURS && (t - PRELUDE_HOURS) % every === 0;
}

function seedOf(log: readonly SimEvent[]): number {
  const start = log[0];
  if (!start || start.type !== 'run.start') throw new Error('replay: log must begin with run.start');
  return start.seed;
}

/**
 * Rebuild state from the log: createState → for each event in order,
 * advance to its hour then apply it → advance to `toT`.
 */
export function replay(log: readonly SimEvent[], toT: number, config: SimConfig = DEFAULT_CONFIG): SimState {
  const seed = seedOf(log);
  const rng = createRng(seed);
  let s = createState(seed, config);
  for (const ev of log) {
    if (ev.t > toT) break; // events after the target hour have not happened yet
    s = advanceTo(s, ev.t, config, rng);
    if (ev.type === 'run.start' || ev.type === 'checkpoint') continue;
    const { t, wallMs, ...action } = ev;
    void t;
    void wallMs;
    s = applyAction(s, action as Action);
  }
  return advanceTo(s, toT, config, rng);
}

/** Replay and compare every checkpoint hash; the console warns on mismatch and trusts replay. */
export function verifyCheckpoints(
  log: readonly SimEvent[],
  config: SimConfig = DEFAULT_CONFIG,
): { ok: boolean; firstMismatchT: number | null } {
  const seed = seedOf(log);
  const rng = createRng(seed);
  let s = createState(seed, config);
  for (const ev of log) {
    s = advanceTo(s, ev.t, config, rng);
    if (ev.type === 'checkpoint') {
      if (hashState(s) !== ev.hash) return { ok: false, firstMismatchT: ev.t };
      continue;
    }
    if (ev.type === 'run.start') continue;
    const { t, wallMs, ...action } = ev;
    void t;
    void wallMs;
    s = applyAction(s, action as Action);
  }
  return { ok: true, firstMismatchT: null };
}
