/**
 * localStorage persistence. Plan §4.6 (T5). Pure over an injected `Storage`.
 *
 * Only the event log and the wall-clock stamp are stored; state is always
 * regenerated by `replay`. Every access is wrapped in try/catch and every
 * malformed record reads as `null`, so a bad save can only ever cost the
 * player a fresh run, never a crash. This module is the only writer; a
 * later SQLite backend would take `SaveRecord` as its row shape.
 */
import type { SimEvent } from '../sim/types';
import { SIM_SPEEDS } from '../sim/time';
import { CONSTANTS } from '../sim/constants';
import type { TimeRecord } from './core/run';

export const SAVE_KEY = 'spaghetti.console.run.v1';

export interface SaveRecord {
  version: number;
  seed: number;
  log: SimEvent[];
  time: TimeRecord;
}

function isRecord(x: unknown): x is Record<string, unknown> {
  return typeof x === 'object' && x !== null;
}

function isFiniteNumber(x: unknown): x is number {
  return typeof x === 'number' && Number.isFinite(x);
}

function isTimeRecord(x: unknown): x is TimeRecord {
  if (!isRecord(x)) return false;
  return (
    isFiniteNumber(x.t) &&
    isFiniteNumber(x.stampMs) &&
    isFiniteNumber(x.carryMs) &&
    typeof x.paused === 'boolean' &&
    (SIM_SPEEDS as readonly number[]).includes(x.speed as number)
  );
}

function isLog(x: unknown): x is SimEvent[] {
  if (!Array.isArray(x) || x.length === 0) return false;
  const first: unknown = x[0];
  if (!isRecord(first) || first.type !== 'run.start') return false;
  return x.every((ev: unknown) => isRecord(ev) && typeof ev.type === 'string' && isFiniteNumber(ev.t));
}

/** Shape-check a parsed value; `version` must equal `expectedVersion`. */
export function parseRecord(raw: unknown, expectedVersion: number = CONSTANTS.SIM_VERSION): SaveRecord | null {
  if (!isRecord(raw)) return null;
  if (raw.version !== expectedVersion) return null;
  if (!isFiniteNumber(raw.seed)) return null;
  if (!isLog(raw.log)) return null;
  if (!isTimeRecord(raw.time)) return null;
  return { version: raw.version, seed: raw.seed, log: raw.log, time: { ...raw.time } };
}

/** Read and validate the saved record; anything wrong → `null`. */
export function load(storage: Storage | null | undefined, expectedVersion: number = CONSTANTS.SIM_VERSION): SaveRecord | null {
  if (!storage) return null;
  let text: string | null;
  try {
    text = storage.getItem(SAVE_KEY);
  } catch {
    return null;
  }
  if (text === null || text === undefined) return null;
  let raw: unknown;
  try {
    raw = JSON.parse(text);
  } catch {
    return null;
  }
  return parseRecord(raw, expectedVersion);
}

/** Write the record; returns false when storage is missing, full or disabled. */
export function save(rec: SaveRecord, storage: Storage | null | undefined): boolean {
  if (!storage) return false;
  try {
    storage.setItem(SAVE_KEY, JSON.stringify(rec));
    return true;
  } catch {
    return false;
  }
}

/** Forget the saved run. */
export function clear(storage: Storage | null | undefined): void {
  if (!storage) return;
  try {
    storage.removeItem(SAVE_KEY);
  } catch {
    /* disabled storage: nothing to clear */
  }
}

/** The page's localStorage when it exists and works; `null` otherwise (SSR, private mode, tests). */
export function safeStorage(): Storage | null {
  try {
    if (typeof localStorage === 'undefined' || localStorage === null) return null;
    const probe = `${SAVE_KEY}.probe`;
    localStorage.setItem(probe, '1');
    localStorage.removeItem(probe);
    return localStorage;
  } catch {
    return null;
  }
}
